import { writable } from 'svelte/store'

let jobs_ = [
  /**
   * 
   *  20 JOBS 
   * 
   **/
  {
    id: 1,
    title: "Environmental practitioner",
    img: "/images/jobs/job-01.png",
    valueChains: [1, 2, 6],
    desc: `Assesses, improves, and gives advice to companies on environmental strategies. Measures the carbon footprint being left by logistics in the FoodBev industry and advises efficient practices that will reduce impact and contribute to a circular economy.`,
    hardSkills: ["Environmental engineering", "geography", "meteorology"],
    softSkills: ["Negotiation", "teamwork", "multicultural"],
    isAtRisk: false,
    isTransforming: false,
  },
  {
    id: 2,
    title: "Energy Catcher",
    img: "/images/jobs/job-02.png",
    valueChains: [2, 6, 10],
    desc: `A professional who advises on how to capture and use the energy from alternative sources (solar, wind, hydro, kinetic, etc.) effectively`,
    hardSkills: ["Mechanical", "Electrical engineering"],
    softSkills: ["Lean manufacturing", " strategic thinking", " analytical thinking", "system thinking"],
    isAtRisk: false,
    isTransforming: false,
  },
  {
    id: 3,
    title: "Water treatment Operator",
    img: "/images/jobs/job-03.png",
    valueChains: [1, 2, 6],
    desc: `A specialist that looks for ways to use water efficiently (involves research, development, and recycling)`,
    hardSkills: ["Engineering science", "physics", "chemistry", "ecology"],
    softSkills: ["Lean manufacturing", "strategic", "system thinking"],
    isAtRisk: false,
    isTransforming: false,
  },
  {
    id: 4,
    title: "Digital Twin Ecosystem Architect",
    img: "/images/jobs/job-04.png",
    valueChains: [1, 2, 10, 8],
    desc: `An IT professional who creates a digital twin for a certain food plant`,
    hardSkills: ["IT", "engineering", "design"],
    softSkills: ["System thinking", "cross-disciplinary thinking", "project-management", "System thinking", "Process thinking"],
    isAtRisk: false,
    isTransforming: false,
  },
  {
    id: 5,
    title: "Digital Twin Ecosystem manager",
    img: "/images/jobs/job-05.png",
    valueChains: [1, 2, 10, 8],
    desc: `A specialist whose responsibility is to manage the digital twin of food plant to optimize the production process`,
    hardSkills: ["Software design", "AutoCAD 3D", "digital twin operation", "management in food manufacturing"],
    softSkills: ["System thinking", "Process thinking"],
    isAtRisk: false,
    isTransforming: false,
  },
  {
    id: 6,
    title: "Sustainable packaging technologist",
    img: "/images/jobs/job-06.png",
    valueChains: [2, 6, 10, 3, 7],
    desc: `A professional who creates ecology-friendly package materials, mostly based on organic substances`,
    hardSkills: ["Biology", "chemistry", "ecology", "food logistics"],
    softSkills: ["Project-management", "teamwork", "cross-disciplinary thinking"],
    isAtRisk: false,
    isTransforming: false,
  },
  {
    id: 7,
    title: "Supply safety consultant",
    img: "/images/jobs/job-07.png",
    valueChains: [2, 9, 3, 6],
    desc: `A professional who helps food and beverage companies to get proper raw materials for safe and high-quality products`,
    hardSkills: ["Microbiology", "biochemistry", "food safety", "risk management"],
    softSkills: ["Communication", "analytical thinking", "critical thinking"],
    isAtRisk: false,
    isTransforming: false,
  },
  {
    id: 8,
    title: "Circulated economy designer",
    img: "/images/jobs/job-08.png",
    valueChains: [1, 2, 6],
    desc: `Elaborates a strategy for full production cycle management, helps managers to implement it, and provides consulting support.`,
    hardSkills: ["Engeneering", "recycling technologies"],
    softSkills: ["System thinking", "communication", "lean manufacturing", "project-management", "teamwork"],
    isAtRisk: false,
    isTransforming: false,
  },
  {
    id: 9,
    title: "Food plant cybersecurity specialist",
    img: "/images/jobs/job-09.png",
    valueChains: [1, 2, 6, 8, 10, 4],
    desc: `Evaluates cybersecurity risks concerning the safety of produced food products and leakage of information about patented technologies`,
    hardSkills: ["IT", "cybersecurity", "knowledge of manufacturing processes", "risk management"],
    softSkills: ["System thinking", "critical thinking"],
    isAtRisk: false,
    isTransforming: false,
  },
  {
    id: 10,
    title: "Food logistics specialist",
    img: "/images/jobs/job-10.png",
    valueChains: [6, 10, 8, 3, 9, 4],
    desc: `A professional who optimizes food logistics in terms of timing, quality control, supply transparency, and environmental impact. Finds new ways to build supply chains in a sustainable way`,
    hardSkills: ["Logistics", "data science", "new technologies in transportation", "understanding of geographical features", "specifics of food storage in certain climate"],
    softSkills: ["System thinking", "critical thinking", "communication", "teamwork"],
    isAtRisk: false,
    isTransforming: false,
  },
  {
    id: 11,
    title: "Food waste recycling specialist",
    img: "/images/jobs/job-11.png",
    valueChains: [1, 2, 6, 10, 9],
    desc: `A professional who comes up with how to extract useful organic compounds from food waste that are suitable for reuse`,
    hardSkills: ["Biochemistry", "food production technology", "recycling technologies"],
    softSkills: ["Lean manufacturing", "analytical thinking", "system thinking", "teamwork"],
    isAtRisk: false,
    isTransforming: false,
  },
  {
    id: 12,
    title: "Architect of blockchain, food & bev",
    img: "/images/jobs/job-12.png",
    valueChains: [2, 4, 8, 10, 6, 3],
    desc: `A specialist who creates blockchain platforms under the requests of the food and beverages industry to make the processes of creating and logistics of food and beverage products more transparent for consumers. And also to prove their high quality`,
    hardSkills: ["Software design", "blockchain", "understanding how local supply chains work"],
    softSkills: ["System thinking", "cross-disciplinary thinking", "project-management"],
    isAtRisk: false,
    isTransforming: false,
  },
  {
    id: 13,
    title: "System modernization engineer",
    img: "/images/jobs/job-13.png",
    valueChains: [2, 6, 10],
    desc: `A specialist who consults the FoodBev companies about available new technologies that will help improve work processes in factories and offices and helps to implement necessary equipment`,
    hardSkills: ["Engineering", "mechanics", "robotics", "software expertise"],
    softSkills: ["Novelty seeking", "communication", "lean manufacturing,system thinking"],
    isAtRisk: false,
    isTransforming: false,
  },
  {
    id: 14,
    title: "Designer of robotic systems",
    img: "/images/jobs/job-14.png",
    valueChains: [2, 6, 10],
    desc: `An IT specialist who designs industrial robots and cyber-physical systems for food and beverage plants to optimize the process of production`,
    hardSkills: ["Engineering", "mechanics", "robotics", "physics", "chemistry", "hardware design", "software expertise"],
    softSkills: ["System thinking", "cross-disciplinary thinking", "lean manufacturing", "project-management"],
    isAtRisk: false,
    isTransforming: false,
  },
  {
    id: 15,
    title: "Climate change data analyst",
    img: "/images/jobs/job-15.png",
    valueChains: [1, 2, 6, 10],
    desc: `A professional, who compiles, analyzes and clarifies data regarding environmental management and climate change that could influence the FoodBev industry. Improves decision-making, including 3D and geospatial visualization, simulation models, system dynamics, and computer-assisted tools for collecting data from different sources, including global data.`,
    hardSkills: ["Ecology", "Geography", "digital modeling", "data science"],
    softSkills: ["Decision-making", "analytical thinking"],
    isAtRisk: false,
    isTransforming: false,
  },
  {
    id: 16,
    title: "Environmental evangelist",
    img: "/images/jobs/job-16.png",
    valueChains: [1, 2, 6, 0],
    desc: `A professional who promotes ecological responsibility on behalf of the FoodBev companies and encourages different stakeholders (including the government) to collaborate. Analyzes existing climate or environmental management legislation, regulations, policies, and practices to determine actual and potential environmental impacts. Communicates research findings to legislators, regulatory agencies, or other stakeholders and recommends new or adapted social and business initiatives, laws, and policies.`,
    hardSkills: ["Ecology", "law", "local specifics of FoodBev business"],
    softSkills: ["Communication", "negotiation", "leadership"],
    isAtRisk: false,
    isTransforming: false,
  },
  {
    id: 17,
    title: "Cost accounting manager",
    img: "/images/jobs/job-17.png",
    valueChains: [2, 6],
    desc: `A professional who develops cost standards for materials and labor, etc., designs and implements cost accounting systems, analyzes production costs and recommends changes, and oversees annual physical inventory. He also hires, trains, and supervises cost and inventory accounting staff.`,
    hardSkills: ["Economy", "Accounting", "Maths", "Coaching", "IT"],
    softSkills: ["Analytical thinking", "critical thinking", "lean manufacturing"],
    isAtRisk: false,
    isTransforming: false,
  },
  {
    id: 18,
    title: "Agriculture sustainability analyst",
    img: "/images/jobs/job-18.png",
    valueChains: [1, 6],
    desc: `A professional who analyses data to determine which crops and cattle breeds are most suitable for different areas based on climate and soil conditions using artificial intelligence (AI). He also conducts research to improve crop production and breeding methods and develop new varieties, and creates plans for farming operations.`,
    hardSkills: ["IT", "Agriculture", "Ecology"],
    softSkills: ["Lean production", "system thinking", "critical thinking", "cross-disciplinary thinking"],
    isAtRisk: false,
    isTransforming: false,
  },
  {
    id: 19,
    title: "Food biochemist",
    img: "/images/jobs/job-19.png",
    valueChains: [1, 2, 6, 10],
    desc: `Plans and conducts complex projects in basic and applied research of organic substances used for food and beverage preparation, manages laboratory teams and monitors the quality of their work, and presents new solutions to food technologists and management.`,
    hardSkills: ["Biology", "Biochemistry", "food technology", "safety", "management"],
    softSkills: ["Project-management", "critical thinking", "cross-disciplinary thinking", "teamwork"],
    isAtRisk: false,
    isTransforming: false,
  },
  {
    id: 20,
    title: "System risk manager",
    img: "/images/jobs/job-20.png",
    valueChains: [1, 2, 6],
    desc: `Conducts risk assessments, collecting and analyzing documentation, statistics, reports, and market trends using AI. Recommends and implements risk management solutions such as insurance, safety, and security policies. Reviews and analyzes various metrics and employee activity that could uncover fraudulent behavior.`,
    hardSkills: ["Risk Management", "IT", "data science", "security", "documentation in FoodBev"],
    softSkills: ["Analytical thinking", " system thinking", " communication"],
    isAtRisk: false,
    isTransforming: false,
  },
  /**
   * 
   *  JOBS AT RISK 
   * 
   **/
  {
    id: 21,
    title: "Operations Supervisor",
    img: "images/jobs/job-21.png",
    valueChains: [11],
    desc: `Optimization of the workflow and automation`,
    hardSkills: [],
    softSkills: [],
    isAtRisk: true,
    isTransforming: false,
  },
  {
    id: 22,
    title: "L & D Facilitators",
    img: "images/jobs/job-22.png",
    valueChains: [11],
    desc: `Online LMS`,
    hardSkills: [],
    softSkills: [],
    isAtRisk: true,
    isTransforming: false,
  },
  {
    id: 23,
    title: "Warehouse Pickers",
    img: "images/jobs/job-23.png",
    valueChains: [11],
    desc: `Automation`,
    hardSkills: [],
    softSkills: [],
    isAtRisk: true,
    isTransforming: false,
  },
  {
    id: 24,
    title: "Stock-takers",
    img: "images/jobs/job-24.png",
    valueChains: [11],
    desc: `Digital analytical systems tell us when we are out`,
    hardSkills: [],
    softSkills: [],
    isAtRisk: true,
    isTransforming: false,
  },
  {
    id: 25,
    title: "Production Planner/buyer",
    img: "images/jobs/job-25.png",
    valueChains: [11],
    desc: `Digital analytical systems will help in procurement planning, so the number of staff members can be reduced.`,
    hardSkills: [],
    softSkills: [],
    isAtRisk: true,
    isTransforming: false,
  },
  {
    id: 26,
    title: "Couriers",
    img: "images/jobs/job-26.png",
    valueChains: [11],
    desc: `Drones and self-driving cars will compete with humans`,
    hardSkills: [],
    softSkills: [],
    isAtRisk: true,
    isTransforming: false,
  },
  {
    id: 27,
    title: "Maintenance staff",
    img: "images/jobs/job-27.png",
    valueChains: [11],
    desc: `Self-correcting technology`,
    hardSkills: [],
    softSkills: [],
    isAtRisk: true,
    isTransforming: false,
  },
  {
    id: 28,
    title: "Supply chain (product to market)",
    img: "images/jobs/job-28.png",
    valueChains: [11],
    desc: `Cutting the mediators by Uber-like platforms`,
    hardSkills: [],
    softSkills: [],
    isAtRisk: true,
    isTransforming: false,
  },
  /**
   * 
   * TRANSFORMING JOBS
   * 
   * 
   **/
  {
    id: 29,
    title: "Operator + Artisan → Equipment Operational specialist",
    img: "images/jobs/job-29.png",
    valueChains: [1, 2],
    desc: `Automatisation is efficient and economically reasonable because it helps cut off production costs. An artisan has no need to do manual labor but has to learn how to work with robots and digital systems`,
    hardSkills: ["Artisan gets upskilled"],
    softSkills: [],
    isAtRisk: false,
    isTransforming: true,
  },
  {
    id: 30,
    title: "Food scientist / Nutritionist",
    img: "images/jobs/job-30.png",
    valueChains: [2, 9, 10],
    desc: `A better understanding of consumer needs, improved tech skills, a better understanding of nutrition`,
    hardSkills: ["Biomedical knowledge", "Data Analysis"],
    softSkills: [],
    isAtRisk: false,
    isTransforming: true,
  },
  {
    id: 31,
    title: "Marketing manager → Customer insight manager",
    img: "images/jobs/job-31.png",
    valueChains: [1, 2, 3, 4, 7, 9],
    desc: ``,
    hardSkills: [],
    softSkills: ["Empathy", "Emotional IQ"],
    isAtRisk: false,
    isTransforming: true,
  },
  {
    id: 32,
    title: "E-commerce designer → Integration software engineer",
    img: "images/jobs/job-32.png",
    valueChains: [1, 2, 3, 4, 7],
    desc: `Systemic integration of multiple parties is needed for making effective digital platforms for e-commerce`,
    hardSkills: ["Combining different software"],
    softSkills: [],
    isAtRisk: false,
    isTransforming: true,
  },
  {
    id: 33,
    title: "Farmworker → farm technician",
    img: "images/jobs/job-33.png",
    valueChains: [1],
    desc: `Farms have become more automated, which provides possibilities to make production much more effective, but it requires some IT skills.`,
    hardSkills: [],
    softSkills: ["Computer skills", "digital skills", "analytics", "Using apps and software", "data interpretation", "decision making"],
    isAtRisk: false,
    isTransforming: true,
  },
  {
    id: 34,
    title: "Food delivery logist",
    img: "images/jobs/job-34.png",
    valueChains: [1, 2, 3, 4, 8, 9],
    desc: `Personalizing food consumption`,
    hardSkills: ["Knowledge of diverse food", "knowing community", "road safety skills", "communication", "drone operating"],
    softSkills: [],
    isAtRisk: false,
    isTransforming: true,
  },
  {
    id: 35,
    title: "Wellness expert",
    img: "images/jobs/job-35.png",
    valueChains: [],
    desc: `Manage more healthy ways of food behavior (working with clients)`,
    hardSkills: ["Change management", "mental and physical health", "people skills", "alternative therapy"],
    softSkills: [],
    isAtRisk: false,
    isTransforming: true,
  },
  {
    id: 36,
    title: "R&D Manager",
    img: "images/jobs/job-36.png",
    valueChains: [1, 2, 10],
    desc: `Additional requirements because of new techs and consumers' demand`,
    hardSkills: ["Additional technical skills"],
    softSkills: [],
    isAtRisk: false,
    isTransforming: true,
  },
];



let valueChains_ = [
/*0*/  { id: 1, map: "map-1.png", img: "images/vcs/vc-01.png", name: "Producers" },
/*1*/  { id: 2, map: "map-1.png", img: "/images/vcs/vc-02.png", name: "Manufacturing & Processing" },
/*2*/  { id: 3, map: "map-1.png", img: "images/vcs/vc-03.png", name: "Wholesalers / Distribution" },
/*3*/  { id: 4, map: "map-1.png", img: "/images/vcs/vc-04.png", name: "Online Marketplace" },
/*5*/  { id: 6, map: "map-1.png", img: "images/vcs/vc-06.png", name: "Sustainability Providers" },
/*6*/  { id: 7, map: "map-1.png", img: "images/vcs/vc-07.png", name: "Retail & Groceries" },
/*7*/  { id: 8, map: "map-1.png", img: "/images/vcs/vc-08.png", name: "Transport & Delivery" },
/*8*/  { id: 9, map: "map-1.png", img: "images/vcs/vc-09.png", name: "Restaurant" },
/*9*/  { id: 10, map: "map-1.png", img: "/images/vcs/vc-10.png", name: "New Product Development" },
/*10*/  { id: 11, map: "map-1.png", img: "images/vcs/vc-11.png", name: "Jobs at Risk" },
];


const valueChains = writable(valueChains_);
const jobs = writable(jobs_);

export { valueChains, jobs };