import { writable } from 'svelte/store'

let jobs_ = [
  {
    id: 1,
    top: "55", left: "15",
    title: "Environmental practitioner",
    img: "/images/jobs/job-01.png",
    valueChains: [1, 2, 6],
    desc: `Assesses, improves, and gives advice to companies on environmental strategies. Measures the carbon footprint being left by logistics in the FoodBev industry and advises efficient practices to cut it back`,
    hardSkills: ["Environmental engineering", "geography", "meteorology"],
    softSkills: ["Negotiation", "teamwork", "multicultural"],
  },
  {
    id: 2,
    top: "20", left: "84.5",
    title: "Energy Catcher",
    img: "/images/jobs/job-02.png",
    valueChains: [2, 6, 10],
    desc: `A professional who advises on how to capture and use the energy from alternative sources (solar, wind, hydro, kinetic, etc.) effectively`,
    hardSkills: ["Mechanical", "Electrical engineering"],
    softSkills: ["Lean manufacturing", " strategic", " analytical", "system thinking"],
  },
  {
    id: 3,
    top: "45", left: "11.75",
    title: "Water treatment Operator",
    img: "/images/jobs/job-03.png",
    valueChains: [1, 2, 6],
    desc: `A specialist that looks for ways to use water efficiently (involves research, development, and recycling)`,
    hardSkills: ["Engineering science", "physics", "chemistry", "ecology"],
    softSkills: ["Lean manufacturing", "strategic", "system thinking"],
  },
  {
    id: 4,
    top: "45", left: "40",
    title: "Digital Twin Ecosystem Architect",
    img: "/images/jobs/job-04.png",
    valueChains: [1, 2, 10, 8],
    desc: `An IT professional who creates a digital twin for a certain food plant`,
    hardSkills: ["IT", "engineering", "design"],
    softSkills: ["System thinking", "cross-disciplinary thinking", "project-management", "System thinking", "Process thinking"],
  },
  {
    id: 5,
    top: "50", left: "30",
    title: "Digital Twin Ecosystem manager",
    img: "/images/jobs/job-05.png",
    valueChains: [1, 2, 10, 8],
    desc: `A specialist whose responsibility is to manage the digital twin of food plant to optimize the production process`,
    hardSkills: ["Software design", "AutoCAD 3D", "digital twin operation", "management in food manufacturing"],
    softSkills: ["System thinking", "Process thinking"],
  },
  {
    id: 6,
    top: "20", left: "56",
    title: "Sustainable packaging technologist",
    img: "/images/jobs/job-06.png",
    valueChains: [2, 6, 10, 3, 7],
    desc: `A professional who creates ecology-friendly package materials, mostly based on organic substances`,
    hardSkills: ["Biology", "chemistry", "ecology", "food logistics"],
    softSkills: ["Project-management", "teamwork", "cross-disciplinary thinking"],
  },
  {
    id: 7,
    top: "58.5", left: "22.5",
    title: "Supply safety consultant",
    img: "/images/jobs/job-06.png",
    valueChains: [2, 9, 3, 6],
    desc: `A professional who helps food and beverage companies to get proper raw materials for safe and high-quality products`,
    hardSkills: ["Microbiology", "biochemistry", "food safety", "risk management"],
    softSkills: ["Communication", "analytical thinking", "critical thinking"],
  },
  {
    id: 8,
    top: "27.5", left: "62.5",
    title: "Circulated economy designer",
    img: "/images/jobs/job-08.png",
    valueChains: [1, 2, 6],
    desc: `Elaborates a strategy for full production cycle management, helps managers to implement it, and provides consulting support.`,
    hardSkills: ["Engeneering", "recycling technologies"],
    softSkills: ["System thinking", "communication", "lean manufacturing", "project-management", "teamwork"],
  },
  {
    id: 9,
    top: "55", left: "75",
    title: "Food plant cybersecurity specialist",
    img: "/images/jobs/job-09.png",
    valueChains: [1, 2, 6, 8, 10, 4],
    desc: `Evaluates cybersecurity risks concerning the safety of produced food products and leakage of information about patented technologies`,
    hardSkills: ["IT", "cybersecurity", "knowledge of manufacturing processes", "risk management"],
    softSkills: ["System thinking", "critical thinking"],
  },
  {
    id: 10,
    top: "54.5", left: "26",
    title: "Food logistics specialist",
    img: "/images/jobs/job-10.png",
    valueChains: [6, 10, 8, 3, 9, 4],
    desc: `A professional who optimizes food logistics in terms of timing, quality control, supply transparency, and environmental impact. Finds new ways to build supply chains in a sustainable way`,
    hardSkills: ["Logistics", "data science", "new technologies in transportation", "understanding of geographical features", "specifics of food storage in certain climate"],
    softSkills: ["System thinking", "critical thinking", "communication", "teamwork"],
  },
  {
    id: 11,
    top: "46", left: "74",
    title: "Food waste recycling specialist",
    img: "/images/jobs/job-11.png",
    valueChains: [1, 2, 6, 10, 9],
    desc: `A professional who comes up with how to extract useful organic compounds from food waste that are suitable for reuse`,
    hardSkills: ["Biochemistry", "food production technology", "recycling technologies"],
    softSkills: ["Lean manufacturing", "analytical thinking", "system thinking", "teamwork"],
  },
  {
    id: 12,
    top: "13.5", left: "41.5",
    title: "Architect of blockchain platforms for food & bev",
    img: "/images/jobs/job-12.png",
    valueChains: [2, 4, 8, 10, 6, 3],
    desc: `A specialist who creates blockchain platforms under the requests of the food and beverages industry to make the processes of creating and logistics of food and beverage products more transparent for consumers. And also to prove their high quality`,
    hardSkills: ["Software design", "blockchain", "understanding how local supply chains work"],
    softSkills: ["System thinking", "cross-disciplinary thinking", "project-management"],
  },
  {
    id: 13,
    top: "45", left: "52.5",
    title: "System modernization engineer",
    img: "/images/jobs/job-13.png",
    valueChains: [2, 6, 10],
    desc: `A specialist who consults the FoodBev companies about available new technologies that will help improve work processes in factories and offices and helps to implement necessary equipment`,
    hardSkills: ["Engineering", "mechanics", "robotics", "software expertise"],
    softSkills: ["Novelty seeking", "communication", "lean manufacturing,system thinking"],
  },
  {
    id: 14,
    top: "57.5", left: "46.5",
    title: "Designer of robotic systems for plants",
    img: "/images/jobs/job-14.png",
    valueChains: [2, 6, 10],
    desc: `An IT specialist who designs industrial robots and cyber-physical systems for food and beverage plants to optimize the process of production`,
    hardSkills: ["Engineering", "mechanics", "robotics", "physics", "chemistry", "hardware design", "software expertise"],
    softSkills: ["System thinking", "cross-disciplinary thinking", "lean manufacturing", "project-management"],
  },
  {
    id: 15,
    top: "14", left: "52.25",
    title: "Climate change data analyst",
    img: "/images/jobs/job-15.png",
    valueChains: [1, 2, 6, 10],
    desc: `A professional, who compiles, analyzes and clarifies data regarding environmental management and climate change that could influence the FoodBev industry. Improves decision-making, including 3D and geospatial visualization, simulation models, system dynamics, and computer-assisted tools for collecting data from different sources, including global data.`,
    hardSkills: ["Ecology", "Geography", "digital modeling", "data science"],
    softSkills: ["Decision-making", "analytical thinking"],
  },
  {
    id: 16,
    top: "20", left: "47.5",
    title: "Environmental evangelist",
    img: "/images/jobs/job-16.png",
    valueChains: [1, 2, 6, 0],
    desc: `A professional who promotes ecological responsibility on behalf of the FoodBev companies and encourages different stakeholders (including the government) to collaborate. Analyzes existing climate or environmental management legislation, regulations, policies, and practices to determine actual and potential environmental impacts. Communicates research findings to legislators, regulatory agencies, or other stakeholders and recommends new or adapted social and business initiatives, laws, and policies.`,
    hardSkills: ["Ecology", "law", "local specifics of FoodBev business"],
    softSkills: ["Communication", "negotiation", "leadership"],
  },
  {
    id: 17,
    top: "10", left: "66.5",
    title: "Cost accounting manager",
    img: "/images/jobs/job-17.png",
    valueChains: [2, 6],
    desc: `A professional who develops cost standards for materials and labor, etc., designs and implements cost accounting systems, analyzes production costs and recommends changes, and oversees annual physical inventory. He also hires, trains, and supervises cost and inventory accounting staff.`,
    hardSkills: ["Economy", "Accounting", "Maths", "Coaching", "IT"],
    softSkills: ["Analytical thinking", "critical thinking", "lean manufacturing"],
  },
  {
    id: 18,
    top: "16.5", left: "12.5",
    title: "Agriculture sustainability analyst",
    img: "/images/jobs/job-18.png",
    valueChains: [1, 6,],
    desc: `A professional who analyses data to determine which crops and cattle breeds are most suitable for different areas based on climate and soil conditions using artificial intelligence (AI). He also conducts research to improve crop production and breeding methods and develop new varieties, and creates plans for farming operations.`,
    hardSkills: ["IT", "Agriculture", "Ecology"],
    softSkills: ["Lean production", "system thinking", "critical thinking", "cross-disciplinary thinking"],
  },
  {
    id: 19,
    top: "48", left: "86",
    title: "Food biochemist",
    img: "/images/jobs/job-19.png",
    valueChains: [1, 2, 6, 10],
    desc: `Plans and conducts complex projects in basic and applied research of organic substances used for food and beverage preparation, manages laboratory teams and monitors the quality of their work, and presents new solutions to food technologists and management.`,
    hardSkills: ["Biology", "Biochemistry", "food technology", "safety", "management"],
    softSkills: ["Project-management", "critical thinking", "cross-disciplinary thinking", "teamwork"],
  },
  {
    id: 20,
    top: "16.5", left: "72",
    title: "System risk manager",
    img: "/images/jobs/job-20.png",
    valueChains: [1, 2, 6],
    desc: `Conducts risk assessments, collecting and analyzing documentation, statistics, reports, and market trends using AI. Recommends and implements risk management solutions such as insurance, safety, and security policies. Reviews and analyzes various metrics and employee activity that could uncover fraudulent behavior.`,
    hardSkills: ["Risk Management", "IT", "data science", "security", "documentation in FoodBev"],
    softSkills: ["Analytical thinking", " system thinking", " communication"],
  },
];

let valueChains_ = [
  {
    id: 1,
    name: "Producers",
  },
  {
    id: 2,
    name: "Food Processor",
  },
  {
    id: 3,
    name: "Wholesalers",
  },
  {
    id: 4,
    name: "Online Shopping",
  },
  {
    id: 5,
    name: "Store",
  },
  {
    id: 6,
    name: "Sustainability",
  },
  {
    id: 7,
    name: "Grocery Shopping",
  },
  {
    id: 8,
    name: "Delivery",
  },
  {
    id: 9,
    name: "Restaurant",
  },
  {
    id: 10,
    name: "Innovators",
  },
];

const valueChains = writable(valueChains_);
const jobs = writable(jobs_);

export { valueChains, jobs };